"use client";

import { Field, FieldLabel, FieldError } from "@repo/ui";
import { Button, Input } from "@repo/ui";
import { useFormContext } from "react-hook-form";
import { LinkBuilderFields } from "@/types/linkBuilder";
import { Shuffle, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import styles from "../LinkBuilder.module.scss";
import { useTRPC } from "@/trpc/client";
import { useQuery } from "@tanstack/react-query";
import { useLinkBuilderStore } from "@/hooks/useLinkBuilder";

export const ShortLinkSection = () => {
  const {
    register,
    watch,
    setValue,
    formState: { errors },
    setError,
    clearErrors
  } = useFormContext<LinkBuilderFields>();

  const [hasAutoGeneratedSlug, setHasAutoGeneratedSlug] = useState<boolean>(false);
  const {selectedLink} = useLinkBuilderStore();

  const destinationUrl = watch("destinationUrl");
  const slug = watch("slug");
  const registerSlug = register('slug');

  const trpc = useTRPC();
  const randomSlug = useQuery(trpc.get.generateAvailableSlug.queryOptions({}, {enabled: false}));
  const relevantSlug = useQuery(
    trpc.get.generateAvailableSlug.queryOptions(
      { destinationUrl },
      { enabled: false },
    ),
  );
  const checkUniqueSlug = useQuery(
    trpc.get.validateSlugAvailability.queryOptions(
      { slug },
      { enabled: false, retry: false},
    ),
  );

  useEffect(() => {
    if (!!slug || hasAutoGeneratedSlug || selectedLink) return;
    const generateSlug = async () => {
      const result = await randomSlug.refetch();

      if (!result.data) return;

      setValue("slug", result.data.data, {
        shouldDirty: false,
      });

      setHasAutoGeneratedSlug(true);
    };

    generateSlug();
  }, [selectedLink, slug, hasAutoGeneratedSlug, randomSlug, setValue]);

  useEffect(() => {
    if (!slug) return;

    if(selectedLink && selectedLink.slug === slug){
      clearErrors('slug');
      return;
    }

    const timer = setTimeout(async () => {
      const result = await checkUniqueSlug.refetch();
      if (result.error) {
        setError("slug", {
          type: "manual",
          message: result.error.message,
        });
      } else {
        clearErrors("slug");
      }
    }, 500);

    return () => clearTimeout(timer);
  }, [slug]);

  const handleShuffle = async () => {
    await randomSlug.refetch();
    if (!randomSlug.data) return;
    const data = randomSlug.data.data;
    setValue("slug", data);
  };

  const handleSmartShuffle = async () => {
    await relevantSlug.refetch();
    if (!relevantSlug || !relevantSlug.data || relevantSlug.isPending) return;
    const smartSlug = relevantSlug.data.data;
    setValue("slug", smartSlug);
  };

  // const handleInputChange = async (e: any) => {
  //   await checkUniqueSlug.refetch();
  //   if(!checkUniqueSlug || checkUniqueSlug.isPending) return;
  //   if (checkUniqueSlug.error) {
  //     setError("slug", { type: "manual", message: checkUniqueSlug.error.message });
  //   }
  // };

  return (
    <>
      <Field>
        <div className={styles.shortLinkHeaderRow}>
          <FieldLabel htmlFor="slug">Short link</FieldLabel>

          <div className={styles.shortLinkActions}>
            <Button
              variant="ghost"
              size="xs"
              onClick={handleShuffle}
              aria-label="Generate random slug"
              title="Generate random slug"
              type="button"
              disabled={randomSlug.isPending}
            >
              <Shuffle size={12} />
            </Button>
            <Button
              variant="ghost"
              size="xs"
              onClick={handleSmartShuffle}
              aria-label="Generate slug from destination"
              title="Generate slug from destination"
              type="button"
              disabled={!destinationUrl || relevantSlug.isPending}
            >
              <Sparkles size={12} />
            </Button>
          </div>
        </div>
        <Input
          id="slug"
          type="text"
          placeholder="Your Slug"
          {...registerSlug}
          // onChange={(e) => {
          //   registerSlug.onChange(e);
          //   handleInputChange(e);
          // }}
          {...register('slug')}
        />
        <FieldError errors={[errors.slug]} />
      </Field>
    </>
  );
};
